name: Build API Interface Specification

on:
  workflow_dispatch:
  push:
    paths:
      - assessment/cloud/spec.yml

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate OpenAPI docs
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: html2
          openapi-file: ./assessment/cloud/spec.yml
          # config-file: angular-generator-config.yml
          command-args: --output ./assessment/cloud/docs

      - name: Upload Specification
        uses: actions/upload-artifact@v2
        with:
          name: cloud-spec
          path: |
            ./assessment/cloud/docs
