name: Build Site

on:
  workflow_dispatch:
  push:
    paths:
      - public/**

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download notes
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-notes.yml
          workflow_conclusion: success
          branch: main
          path: notes

      - run: cp -r ./notes/notes/handouts ./public

      - name: Download slides
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-slides.yml
          workflow_conclusion: success
          branch: main
          path: slides

      - run: mkdir ./public/slides && cp slides/Slides-*/* ./public/slides

      - name: Publish GH Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public