name: Build Notes

on:
  workflow_dispatch:
  push:
    paths:
      - notes/**

jobs:
  build-notes:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Disable git owner warning
        run: git config --global safe.directory '*'

      - name: Correct last modified
        run: ./.github/workflows/set-last-updated.sh

      - name: Compile Notes
        run: ./bin/build_notes.sh

      - name: Upload Slides
        uses: actions/upload-artifact@v4
        with:
          name: notes
          path: |
            ./dist/**/*.pdf
            ./dist/**/*.html
            ./dist/**/*.css
            ./dist/**/*.svg
            ./dist/**/*.png
            ./dist/**/*.jpg
            ./dist/**/*.jpeg
            ./dist/**/*.gif

  
