name: Build Assessment

on:
  workflow_dispatch:
  push:
    paths:
      - assessment/**

jobs:
  build-assessment:
    runs-on: ubuntu-latest
    container: braewebb/pandoc:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install latex dependencies
        run: ./.github/workflows/latex-dependencies.sh

      - name: Correct last modified
        run: ./.github/workflows/set-last-updated.sh

      - name: Compile Assessment
        run: ./bin/build_assessment.sh

      - name: Upload Specs
        uses: actions/upload-artifact@v3
        with:
          name: assessment
          path: |
            ./dist/**/*.pdf
  
