name: Build Slides

on:
  workflow_dispatch:
  push:
    paths:
      - slides/**

jobs:
  build-notes:
    runs-on: ubuntu-latest
    container: braewebb/pandoc:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup ID
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Install latex dependencies
        run: |
          tlmgr update --self
          tlmgr install cabin
          tlmgr install fontaxes
          tlmgr install tcolorbox
          tlmgr install environ
          tlmgr install datetime
          tlmgr install fmtcount
          tlmgr install filemod
          tlmgr install currfile
          tlmgr install textpos
          tlmgr install stackengine

      - name: Correct last modified
        run: ./.github/workflows/set-last-updated.sh

      - name: Compile Slides
        run: ./bin/build_slides.sh

      - name: Upload Slides
        uses: actions/upload-artifact@v2
        with:
          name: slides
          path: |
            ./dist/**/*.pdf
