name: Build Practicals

on:
  workflow_dispatch:
  push:
    paths:
      - practicals/**

jobs:
  build-notes:
    runs-on: ubuntu-latest
    container: braewebb/pandoc:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Java
        run: sudo apt-get install -y default-jre

      - name: Install latex dependencies
        run: ./.github/workflows/latex-dependencies.sh

      - name: Correct last modified
        run: ./.github/workflows/set-last-updated.sh

      - name: Compile Practicals
        run: ./bin/build_practicals.sh

      - name: Upload Practicals
        uses: actions/upload-artifact@v2
        with:
          name: practicals
          path: |
            ./dist/**/*.pdf
  
