name: Build Slides

on:
  workflow_dispatch:
  push:
    paths:
      - slides/**

jobs:
  build-slides:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Disable git owner warning
        run: git config --global safe.directory '*'

      - name: Correct last modified
        run: ./.github/workflows/set-last-updated.sh

      - name: Compile Slides
        run: ./bin/build_slides.sh

      - name: Upload Slides
        uses: actions/upload-artifact@v3
        with:
          name: slides
          path: |
            ./dist/**/*.pdf
