name: Build Tutorials

on:
  workflow_dispatch:
  push:
    paths:
      - tutorials/**

jobs:
  build-notes:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Correct last modified
        run: ./.github/workflows/set-last-updated.sh

      - name: Compile Tutorials
        run: ./bin/build_tutorials.sh

      - name: Upload Slides
        uses: actions/upload-artifact@v3
        with:
          name: tutorials
          path: |
            ./dist/**/*.pdf
  
