name: Build Tutorials

on:
  workflow_dispatch:
  push:
    paths:
      - tutorials/**

jobs:
  build-notes:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Disable git owner warning
        run: git config --global safe.directory '*'

      - name: Correct last modified
        run: ./.github/workflows/set-last-updated.sh

      - name: Compile Tutorials
        run: ./bin/build_tutorials.sh

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Chatterbox Spec
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: html2
          openapi-file: ./tutorials/chatterbox/spec.yml
          command-args: --output ./dist/tutorials/chatterbox-spec --template-dir ./assessment/cloud/docs-template

      - name: Upload Slides
        uses: actions/upload-artifact@v3
        with:
          name: tutorials
          path: |
            ./dist/**/*
  
