name: Build Practicals

on:
  workflow_dispatch:
  push:
    paths:
      - practicals/**

jobs:
  build-practicals:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java
        run: apt-get update && apt-get install -y default-jre graphviz

      - name: Correct last modified
        run: ./.github/workflows/set-last-updated.sh

      - name: Compile Practicals
        run: ./bin/build_practicals.sh

      - name: Upload Practicals
        uses: actions/upload-artifact@v3
        with:
          name: practicals
          path: |
            ./dist/**/*.pdf
  
